export const ACTION_DESCRIPTION = "ACTION_DESCRIPTION";
export const TOGGLE_MUTE = "TOGGLE_MUTE";
export const SET_AUDIO = "SET_AUDIO";
export const SET_TIMER = "SET_TIMER";
export const SET_TIMER_DISPLAY = "SET_TIMER_DISPLAY";
export const TOGGLE_TIME_END_NOTIFICION = "TOGGLE_TIME_END_NOTIFICION";
export const TOGGLE_TIMER_ON_BROWSER = "TOGGLE_TIMER_ON_BROWSER";
export const TOGGLE_WEB_NOTIFICATION = "TOGGLE_WEB_NOTIFICATION";
export const SET_TOTAL_SESSION = "SET_TOTAL_SESSION";
export const SET_CURRENT_SESSION = "SET_CURRENT_SESSION";
export const TOGGLE_ACTIVATE_IMAGE = "TOGGLE_ACTIVATE_IMAGE";
export const TOGGLE_WORK_IN_SESSION = "TOGGLE_WORK_IN_SESSION";
export const SET_SHORT_BREAK = "SET_SHORT_BREAK";
export const SET_LONG_BREAK = "SET_LONG_BREAK";
export const TOGGLE_AUTO_START = "TOGGLE_AUTO_START";
export const TOGGLE_BREAK_END_NOTIFICATION = "TOGGLE_BREAK_END_NOTIFICATION";
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_BACKGROUND_SHUFFLE_TIME = "SET_BACKGROUND_SHUFFLE_TIME";

export const SET_USERNAME = "SET_USERNAME";
export const SET_EMAIL = "SET_EMAIL";
export const SET_FAMILY_NAME = "SET_FAMILY_NAME";
export const SET_GIVEN_NAME = "SET_GIVEN_NAME";

export const SET_SETTINGS = "SET_SETTINGS";
export const SET_USER_ACCOUNT = "SET_USER_ACCOUNT";
export const SET_SETTING_LOADED_FROM_BACKEND =
  "SET_SETTING_LOADED_FROM_BACKEND";
